language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-4.9
            - g++-4.9
      env:
        - CCOMPILER=gcc-4.9
        - CXXCOMPILER=g++-4.9
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-5
            - g++-5
      env:
        - CCOMPILER=gcc-5
        - CXXCOMPILER=g++-5
    - os: linux
      dist: xenial
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env:
        - CCOMPILER=gcc-6
        - CXXCOMPILER=g++-6
    - os: linux
      dist: focal
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - CCOMPILER=gcc-7
        - CXXCOMPILER=g++-7
    - os: osx
      osx_image: xcode12.2
      compiler: clang
      env:
        - CCOMPILER=clang
        - CXXCOMPILER=clang++
    - os: osx
      osx_image: xcode11.3
      compiler: clang
      env:
        - CCOMPILER=clang
        - CXXCOMPILER=clang++
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env:
        - CCOMPILER=clang
        - CXXCOMPILER=clang++
    - os: osx
      osx_image: xcode12.2
      compiler: gcc
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++
    - os: osx
      osx_image: xcode11.3
      compiler: gcc
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++
    - os: osx
      osx_image: xcode9.4
      compiler: gcc
      env:
        - CCOMPILER=gcc
        - CXXCOMPILER=g++

before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update -qq; fi
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install -y gtk+3.0 libgtk-3-dev libwebkit2gtk-4.0-dev libcurl4-openssl-dev; fi

install:
  - ${CCOMPILER} --version
  - ${CXXCOMPILER} --version

script:
  - make all CC=${CCOMPILER} CXX=${CXXCOMPILER}

