version: 3.0.{build}

image: Visual Studio 2022

configuration:
  - Debug
  - Release

platform:
  - x86
  - x64

install:
  - ps: >-
      git submodule update -q --init --recursive

      .\setup-external-dependencies.ps1
build:
    project: .\ZPatcher.sln
    verbosity: minimal
